---

- hosts: localhost
  vars_prompt:
    - name: email
      prompt: Email for git?
      private: false
  tasks:
    - name: Bash
      block:
        - blockinfile:
            path: ~/.bashrc
            block: |
              if [ -d ~/.bashrc.d ]; then
                for rc in ~/.bashrc.d/*; do
                  if [ -f "$rc" ]; then
                    . "$rc"
                  fi
                done
              fi
        - file:
            path: ~/.bashrc.d
            state: directory

    - name: FZF
      block:
        - package:
            name: fzf
            state: present
          become: true
      rescue:
        - git:
            repo: https://github.com/junegunn/fzf.git
            dest: ~/.fzf
            depth: 1
        - shell: ~/.fzf/install

    - name: Git
      block:
        - package:
            name:
              - git
            state: present
          become: true
        - template:
            src: template/gitconfig
            dest: ~/.gitconfig

    - name: Tmux
      block:
        - package:
            name:
              - tmux
            state: present
          become: true
        - git:
            repo: https://github.com/tmux-plugins/tpm
            dest: ~/.tmux/plugins/tpm
            depth: 1
        - template:
            src: template/tmux.conf
            dest: ~/.tmux.conf
        - template:
            src: template/tmux.bashrc
            dest: ~/.bashrc.d/tmux.bashrc

    - name: Vi
      block:
        - package:
            name:
              - vim
            state: present
          become: true
        - template:
            src: template/vimrc
            dest: ~/.vimrc

    - name: editorconfig
      block:
        - package:
            name:
              - editorconfig
            state: present
          become: true
        - template:
            src: template/editorconfig
            dest: ~/.editorconfig
